interface Country {
    id: number;
    name: string;
    short_code: string;
    long_code: string;
    phone_code: string;
    phone_format: string;
    latitude: number;
    longitude: number;
    status: "active" | "inactive"; // Assuming status can only be "active" or "inactive"
    order_no: number;
}

export const countries: Country[] = [
    {
        id: 1,
        name: "Afghanistan",
        short_code: "AF",
        long_code: "0",
        phone_code: "93",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 2,
        name: "Albania",
        short_code: "AL",
        long_code: "0",
        phone_code: "355",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 3,
        name: "Algeria",
        short_code: "DZ",
        long_code: "0",
        phone_code: "213",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 4,
        name: "American Samoa",
        short_code: "AS",
        long_code: "0",
        phone_code: "1684",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 5,
        name: "Andorra",
        short_code: "AD",
        long_code: "0",
        phone_code: "376",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 6,
        name: "Angola",
        short_code: "AO",
        long_code: "0",
        phone_code: "244",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 7,
        name: "Anguilla",
        short_code: "AI",
        long_code: "0",
        phone_code: "1264",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 8,
        name: "Antarctica",
        short_code: "AQ",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 9,
        name: "Antigua and Barbuda",
        short_code: "AG",
        long_code: "0",
        phone_code: "1268",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 10,
        name: "Argentina",
        short_code: "AR",
        long_code: "0",
        phone_code: "54",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 11,
        name: "Armenia",
        short_code: "AM",
        long_code: "0",
        phone_code: "374",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 12,
        name: "Aruba",
        short_code: "AW",
        long_code: "0",
        phone_code: "297",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 13,
        name: "Australia",
        short_code: "AU",
        long_code: "0",
        phone_code: "61",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 14,
        name: "Austria",
        short_code: "AT",
        long_code: "0",
        phone_code: "43",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 15,
        name: "Azerbaijan",
        short_code: "AZ",
        long_code: "0",
        phone_code: "994",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 16,
        name: "countries.bahamas_the",
        short_code: "BS",
        long_code: "0",
        phone_code: "1242",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 17,
        name: "Bahrain",
        short_code: "BH",
        long_code: "0",
        phone_code: "973",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 18,
        name: "Bangladesh",
        short_code: "BD",
        long_code: "0",
        phone_code: "880",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 19,
        name: "Barbados",
        short_code: "BB",
        long_code: "0",
        phone_code: "1246",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 20,
        name: "Belarus",
        short_code: "BY",
        long_code: "0",
        phone_code: "375",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 21,
        name: "Belgium",
        short_code: "BE",
        long_code: "0",
        phone_code: "32",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 22,
        name: "Belize",
        short_code: "BZ",
        long_code: "0",
        phone_code: "501",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 23,
        name: "Benin",
        short_code: "BJ",
        long_code: "0",
        phone_code: "229",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 24,
        name: "Bermuda",
        short_code: "BM",
        long_code: "0",
        phone_code: "1441",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 25,
        name: "Bhutan",
        short_code: "BT",
        long_code: "0",
        phone_code: "975",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 26,
        name: "Bolivia",
        short_code: "BO",
        long_code: "0",
        phone_code: "591",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 27,
        name: "Bosnia and Herzegovina",
        short_code: "BA",
        long_code: "0",
        phone_code: "387",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 28,
        name: "Botswana",
        short_code: "BW",
        long_code: "0",
        phone_code: "267",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 29,
        name: "Bouvet Island",
        short_code: "BV",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 30,
        name: "Brazil",
        short_code: "BR",
        long_code: "0",
        phone_code: "55",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 31,
        name: "British Indian Ocean Territory",
        short_code: "IO",
        long_code: "0",
        phone_code: "246",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 32,
        name: "Brunei",
        short_code: "BN",
        long_code: "0",
        phone_code: "673",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 33,
        name: "Bulgaria",
        short_code: "BG",
        long_code: "0",
        phone_code: "359",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 34,
        name: "Burkina Faso",
        short_code: "BF",
        long_code: "0",
        phone_code: "226",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 35,
        name: "Burundi",
        short_code: "BI",
        long_code: "0",
        phone_code: "257",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 36,
        name: "Cambodia",
        short_code: "KH",
        long_code: "0",
        phone_code: "855",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 37,
        name: "Cameroon",
        short_code: "CM",
        long_code: "0",
        phone_code: "237",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 38,
        name: "Canada",
        short_code: "CA",
        long_code: "0",
        phone_code: "1",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 39,
        name: "Cape Verde",
        short_code: "CV",
        long_code: "0",
        phone_code: "238",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 40,
        name: "Cayman Islands",
        short_code: "KY",
        long_code: "0",
        phone_code: "1345",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 41,
        name: "Central African Republic",
        short_code: "CF",
        long_code: "0",
        phone_code: "236",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 42,
        name: "Chad",
        short_code: "TD",
        long_code: "0",
        phone_code: "235",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 43,
        name: "Chile",
        short_code: "CL",
        long_code: "0",
        phone_code: "56",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 44,
        name: "China",
        short_code: "CN",
        long_code: "0",
        phone_code: "86",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 45,
        name: "Christmas Island",
        short_code: "CX",
        long_code: "0",
        phone_code: "61",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 46,
        name: "countries.cocos_keeling_islands",
        short_code: "CC",
        long_code: "0",
        phone_code: "672",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 47,
        name: "Colombia",
        short_code: "CO",
        long_code: "0",
        phone_code: "57",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 48,
        name: "Comoros",
        short_code: "KM",
        long_code: "0",
        phone_code: "269",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 49,
        name: "countries.republic_of_the_congo",
        short_code: "CG",
        long_code: "0",
        phone_code: "242",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 50,
        name: "countries.democratic_republic_of_the_congo",
        short_code: "CD",
        long_code: "0",
        phone_code: "242",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 51,
        name: "Cook Islands",
        short_code: "CK",
        long_code: "0",
        phone_code: "682",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 52,
        name: "Costa Rica",
        short_code: "CR",
        long_code: "0",
        phone_code: "506",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 53,
        name: "countries.cote_divoire_ivory_coast",
        short_code: "CI",
        long_code: "0",
        phone_code: "225",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 54,
        name: "countries.croatia_hrvatska",
        short_code: "HR",
        long_code: "0",
        phone_code: "385",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 55,
        name: "Cuba",
        short_code: "CU",
        long_code: "0",
        phone_code: "53",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 56,
        name: "Cyprus",
        short_code: "CY",
        long_code: "0",
        phone_code: "357",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 57,
        name: "Czech Republic",
        short_code: "CZ",
        long_code: "0",
        phone_code: "420",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 58,
        name: "Denmark",
        short_code: "DK",
        long_code: "0",
        phone_code: "45",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 59,
        name: "Djibouti",
        short_code: "DJ",
        long_code: "0",
        phone_code: "253",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 60,
        name: "Dominica",
        short_code: "DM",
        long_code: "0",
        phone_code: "1767",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 61,
        name: "Dominican Republic",
        short_code: "DO",
        long_code: "0",
        phone_code: "1809",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 62,
        name: "countries.east_timor",
        short_code: "TP",
        long_code: "0",
        phone_code: "670",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 63,
        name: "Ecuador",
        short_code: "EC",
        long_code: "0",
        phone_code: "593",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 64,
        name: "Egypt",
        short_code: "EG",
        long_code: "0",
        phone_code: "20",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 65,
        name: "El Salvador",
        short_code: "SV",
        long_code: "0",
        phone_code: "503",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 66,
        name: "Equatorial Guinea",
        short_code: "GQ",
        long_code: "0",
        phone_code: "240",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 67,
        name: "Eritrea",
        short_code: "ER",
        long_code: "0",
        phone_code: "291",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 68,
        name: "Estonia",
        short_code: "EE",
        long_code: "0",
        phone_code: "372",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 69,
        name: "Ethiopia",
        short_code: "ET",
        long_code: "0",
        phone_code: "251",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 70,
        name: "countries.external_territories_of_australia",
        short_code: "XA",
        long_code: "0",
        phone_code: "61",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 71,
        name: "Falkland Islands",
        short_code: "FK",
        long_code: "0",
        phone_code: "500",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 72,
        name: "Faroe Islands",
        short_code: "FO",
        long_code: "0",
        phone_code: "298",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 73,
        name: "countries.fiji_islands",
        short_code: "FJ",
        long_code: "0",
        phone_code: "679",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 74,
        name: "Finland",
        short_code: "FI",
        long_code: "0",
        phone_code: "358",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 75,
        name: "France",
        short_code: "FR",
        long_code: "0",
        phone_code: "33",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 76,
        name: "French Guiana",
        short_code: "GF",
        long_code: "0",
        phone_code: "594",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 77,
        name: "French Polynesia",
        short_code: "PF",
        long_code: "0",
        phone_code: "689",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 78,
        name: "French Southern Territories",
        short_code: "TF",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 79,
        name: "Gabon",
        short_code: "GA",
        long_code: "0",
        phone_code: "241",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 80,
        name: "countries.gambia_the",
        short_code: "GM",
        long_code: "0",
        phone_code: "220",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 81,
        name: "Georgia",
        short_code: "GE",
        long_code: "0",
        phone_code: "995",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 82,
        name: "Germany",
        short_code: "DE",
        long_code: "0",
        phone_code: "49",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 83,
        name: "Ghana",
        short_code: "GH",
        long_code: "0",
        phone_code: "233",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 84,
        name: "Gibraltar",
        short_code: "GI",
        long_code: "0",
        phone_code: "350",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 85,
        name: "Greece",
        short_code: "GR",
        long_code: "0",
        phone_code: "30",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 86,
        name: "Greenland",
        short_code: "GL",
        long_code: "0",
        phone_code: "299",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 87,
        name: "Grenada",
        short_code: "GD",
        long_code: "0",
        phone_code: "1473",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 88,
        name: "Guadeloupe",
        short_code: "GP",
        long_code: "0",
        phone_code: "590",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 89,
        name: "Guam",
        short_code: "GU",
        long_code: "0",
        phone_code: "1671",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 90,
        name: "Guatemala",
        short_code: "GT",
        long_code: "0",
        phone_code: "502",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 91,
        name: "countries.guernsey_and_alderney",
        short_code: "XU",
        long_code: "0",
        phone_code: "44",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 92,
        name: "Guinea",
        short_code: "GN",
        long_code: "0",
        phone_code: "224",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 93,
        name: "countries.guinea_bissau",
        short_code: "GW",
        long_code: "0",
        phone_code: "245",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 94,
        name: "Guyana",
        short_code: "GY",
        long_code: "0",
        phone_code: "592",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 95,
        name: "Haiti",
        short_code: "HT",
        long_code: "0",
        phone_code: "509",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 96,
        name: "countries.heard_and_mcdonald_islands",
        short_code: "HM",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 97,
        name: "Honduras",
        short_code: "HN",
        long_code: "0",
        phone_code: "504",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 98,
        name: "countries.hong_kong_sar",
        short_code: "HK",
        long_code: "0",
        phone_code: "852",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 99,
        name: "Hungary",
        short_code: "HU",
        long_code: "0",
        phone_code: "36",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 100,
        name: "Iceland",
        short_code: "IS",
        long_code: "0",
        phone_code: "354",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 101,
        name: "India",
        short_code: "IN",
        long_code: "0",
        phone_code: "91",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 102,
        name: "Indonesia",
        short_code: "ID",
        long_code: "0",
        phone_code: "62",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 103,
        name: "Iran",
        short_code: "IR",
        long_code: "0",
        phone_code: "98",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 104,
        name: "Iraq",
        short_code: "IQ",
        long_code: "0",
        phone_code: "964",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 105,
        name: "Ireland",
        short_code: "IE",
        long_code: "0",
        phone_code: "353",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 106,
        name: "Israel",
        short_code: "IL",
        long_code: "0",
        phone_code: "972",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 107,
        name: "Italy",
        short_code: "IT",
        long_code: "0",
        phone_code: "39",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 108,
        name: "Jamaica",
        short_code: "JM",
        long_code: "0",
        phone_code: "1876",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 109,
        name: "Japan",
        short_code: "JP",
        long_code: "0",
        phone_code: "81",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 110,
        name: "Jersey",
        short_code: "XJ",
        long_code: "0",
        phone_code: "44",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 111,
        name: "Jordan",
        short_code: "JO",
        long_code: "0",
        phone_code: "962",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 112,
        name: "Kazakhstan",
        short_code: "KZ",
        long_code: "0",
        phone_code: "7",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 113,
        name: "Kenya",
        short_code: "KE",
        long_code: "0",
        phone_code: "254",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 114,
        name: "Kiribati",
        short_code: "KI",
        long_code: "0",
        phone_code: "686",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 115,
        name: "countries.korea_north",
        short_code: "KP",
        long_code: "0",
        phone_code: "850",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 116,
        name: "countries.korea_south",
        short_code: "KR",
        long_code: "0",
        phone_code: "82",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 117,
        name: "Kuwait",
        short_code: "KW",
        long_code: "0",
        phone_code: "965",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 118,
        name: "Kyrgyzstan",
        short_code: "KG",
        long_code: "0",
        phone_code: "996",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 119,
        name: "Laos",
        short_code: "LA",
        long_code: "0",
        phone_code: "856",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 120,
        name: "Latvia",
        short_code: "LV",
        long_code: "0",
        phone_code: "371",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 121,
        name: "Lebanon",
        short_code: "LB",
        long_code: "0",
        phone_code: "961",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 122,
        name: "Lesotho",
        short_code: "LS",
        long_code: "0",
        phone_code: "266",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 123,
        name: "Liberia",
        short_code: "LR",
        long_code: "0",
        phone_code: "231",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 124,
        name: "Libya",
        short_code: "LY",
        long_code: "0",
        phone_code: "218",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 125,
        name: "Liechtenstein",
        short_code: "LI",
        long_code: "0",
        phone_code: "423",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 126,
        name: "Lithuania",
        short_code: "LT",
        long_code: "0",
        phone_code: "370",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 127,
        name: "Luxembourg",
        short_code: "LU",
        long_code: "0",
        phone_code: "352",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 128,
        name: "countries.macau_sar",
        short_code: "MO",
        long_code: "0",
        phone_code: "853",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 129,
        name: "Macedonia",
        short_code: "MK",
        long_code: "0",
        phone_code: "389",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 130,
        name: "Madagascar",
        short_code: "MG",
        long_code: "0",
        phone_code: "261",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 131,
        name: "Malawi",
        short_code: "MW",
        long_code: "0",
        phone_code: "265",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 132,
        name: "Malaysia",
        short_code: "MY",
        long_code: "0",
        phone_code: "60",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 133,
        name: "Maldives",
        short_code: "MV",
        long_code: "0",
        phone_code: "960",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 134,
        name: "Mali",
        short_code: "ML",
        long_code: "0",
        phone_code: "223",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 135,
        name: "Malta",
        short_code: "MT",
        long_code: "0",
        phone_code: "356",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 136,
        name: "countries.man_isle_of",
        short_code: "XM",
        long_code: "0",
        phone_code: "44",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 137,
        name: "Marshall Islands",
        short_code: "MH",
        long_code: "0",
        phone_code: "692",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 138,
        name: "Martinique",
        short_code: "MQ",
        long_code: "0",
        phone_code: "596",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 139,
        name: "Mauritania",
        short_code: "MR",
        long_code: "0",
        phone_code: "222",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 140,
        name: "Mauritius",
        short_code: "MU",
        long_code: "0",
        phone_code: "230",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 141,
        name: "Mayotte",
        short_code: "YT",
        long_code: "0",
        phone_code: "269",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 142,
        name: "Mexico",
        short_code: "MX",
        long_code: "0",
        phone_code: "52",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 143,
        name: "Micronesia",
        short_code: "FM",
        long_code: "0",
        phone_code: "691",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 144,
        name: "Moldova",
        short_code: "MD",
        long_code: "0",
        phone_code: "373",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 145,
        name: "Monaco",
        short_code: "MC",
        long_code: "0",
        phone_code: "377",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 146,
        name: "Mongolia",
        short_code: "MN",
        long_code: "0",
        phone_code: "976",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 147,
        name: "Montserrat",
        short_code: "MS",
        long_code: "0",
        phone_code: "1664",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 148,
        name: "Morocco",
        short_code: "MA",
        long_code: "0",
        phone_code: "212",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 149,
        name: "Mozambique",
        short_code: "MZ",
        long_code: "0",
        phone_code: "258",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 150,
        name: "countries.myanmar",
        short_code: "MM",
        long_code: "0",
        phone_code: "95",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 151,
        name: "Namibia",
        short_code: "NA",
        long_code: "0",
        phone_code: "264",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 152,
        name: "Nauru",
        short_code: "NR",
        long_code: "0",
        phone_code: "674",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 153,
        name: "Nepal",
        short_code: "NP",
        long_code: "0",
        phone_code: "977",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 154,
        name: "Netherlands Antilles",
        short_code: "AN",
        long_code: "0",
        phone_code: "599",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 155,
        name: "countries.netherlands_the",
        short_code: "NL",
        long_code: "0",
        phone_code: "31",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 156,
        name: "New Caledonia",
        short_code: "NC",
        long_code: "0",
        phone_code: "687",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 157,
        name: "New Zealand",
        short_code: "NZ",
        long_code: "0",
        phone_code: "64",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 158,
        name: "Nicaragua",
        short_code: "NI",
        long_code: "0",
        phone_code: "505",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 159,
        name: "Niger",
        short_code: "NE",
        long_code: "0",
        phone_code: "227",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 160,
        name: "Nigeria",
        short_code: "NG",
        long_code: "0",
        phone_code: "234",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 161,
        name: "Niue",
        short_code: "NU",
        long_code: "0",
        phone_code: "683",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 162,
        name: "Norfolk Island",
        short_code: "NF",
        long_code: "0",
        phone_code: "672",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 163,
        name: "Northern Mariana Islands",
        short_code: "MP",
        long_code: "0",
        phone_code: "1670",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 164,
        name: "Norway",
        short_code: "NO",
        long_code: "0",
        phone_code: "47",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 165,
        name: "Oman",
        short_code: "OM",
        long_code: "0",
        phone_code: "968",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 166,
        name: "Pakistan",
        short_code: "PK",
        long_code: "0",
        phone_code: "92",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 167,
        name: "Palau",
        short_code: "PW",
        long_code: "0",
        phone_code: "680",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 168,
        name: "countries.palestinian_territory_occupied",
        short_code: "PS",
        long_code: "0",
        phone_code: "970",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 169,
        name: "Panama",
        short_code: "PA",
        long_code: "0",
        phone_code: "507",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 170,
        name: "Papua New Guinea",
        short_code: "PG",
        long_code: "0",
        phone_code: "675",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 171,
        name: "Paraguay",
        short_code: "PY",
        long_code: "0",
        phone_code: "595",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 172,
        name: "Peru",
        short_code: "PE",
        long_code: "0",
        phone_code: "51",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 173,
        name: "Philippines",
        short_code: "PH",
        long_code: "0",
        phone_code: "63",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 174,
        name: "countries.pitcairn_island",
        short_code: "PN",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 175,
        name: "Poland",
        short_code: "PL",
        long_code: "0",
        phone_code: "48",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 176,
        name: "Portugal",
        short_code: "PT",
        long_code: "0",
        phone_code: "351",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 177,
        name: "Puerto Rico",
        short_code: "PR",
        long_code: "0",
        phone_code: "1787",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 178,
        name: "Qatar",
        short_code: "QA",
        long_code: "0",
        phone_code: "974",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 179,
        name: "Réunion",
        short_code: "RE",
        long_code: "0",
        phone_code: "262",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 180,
        name: "Romania",
        short_code: "RO",
        long_code: "0",
        phone_code: "40",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 181,
        name: "Russia",
        short_code: "RU",
        long_code: "0",
        phone_code: "7",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 182,
        name: "Rwanda",
        short_code: "RW",
        long_code: "0",
        phone_code: "250",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 183,
        name: "Saint Helena",
        short_code: "SH",
        long_code: "0",
        phone_code: "290",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 184,
        name: "Saint Kitts and Nevis",
        short_code: "KN",
        long_code: "0",
        phone_code: "1869",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 185,
        name: "Saint Lucia",
        short_code: "LC",
        long_code: "0",
        phone_code: "1758",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 186,
        name: "Saint Pierre and Miquelon",
        short_code: "PM",
        long_code: "0",
        phone_code: "508",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 187,
        name: "Saint Vincent and the Grenadines",
        short_code: "VC",
        long_code: "0",
        phone_code: "1784",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 188,
        name: "Samoa",
        short_code: "WS",
        long_code: "0",
        phone_code: "684",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 189,
        name: "San Marino",
        short_code: "SM",
        long_code: "0",
        phone_code: "378",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 190,
        name: "São Tomé and Príncipe",
        short_code: "ST",
        long_code: "0",
        phone_code: "239",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 191,
        name: "Saudi Arabia",
        short_code: "SA",
        long_code: "0",
        phone_code: "966",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 192,
        name: "Senegal",
        short_code: "SN",
        long_code: "0",
        phone_code: "221",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 193,
        name: "Serbia",
        short_code: "RS",
        long_code: "0",
        phone_code: "381",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 194,
        name: "Seychelles",
        short_code: "SC",
        long_code: "0",
        phone_code: "248",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 195,
        name: "Sierra Leone",
        short_code: "SL",
        long_code: "0",
        phone_code: "232",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 196,
        name: "Singapore",
        short_code: "SG",
        long_code: "0",
        phone_code: "65",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 197,
        name: "Slovakia",
        short_code: "SK",
        long_code: "0",
        phone_code: "421",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 198,
        name: "Slovenia",
        short_code: "SI",
        long_code: "0",
        phone_code: "386",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 199,
        name: "countries.smaller_territories_of_the_uk",
        short_code: "XG",
        long_code: "0",
        phone_code: "44",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 200,
        name: "Solomon Islands",
        short_code: "SB",
        long_code: "0",
        phone_code: "677",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 201,
        name: "Somalia",
        short_code: "SO",
        long_code: "0",
        phone_code: "252",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 202,
        name: "South Africa",
        short_code: "ZA",
        long_code: "0",
        phone_code: "27",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 203,
        name: "countries.south_georgia",
        short_code: "GS",
        long_code: "0",
        phone_code: "0",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 204,
        name: "countries.south_sudan",
        short_code: "SS",
        long_code: "0",
        phone_code: "211",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 205,
        name: "Spain",
        short_code: "ES",
        long_code: "0",
        phone_code: "34",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 206,
        name: "Sri Lanka",
        short_code: "LK",
        long_code: "0",
        phone_code: "94",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 207,
        name: "Sudan",
        short_code: "SD",
        long_code: "0",
        phone_code: "249",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 208,
        name: "Suriname",
        short_code: "SR",
        long_code: "0",
        phone_code: "597",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 209,
        name: "countries.svalbard_and_jan_mayen_islands",
        short_code: "SJ",
        long_code: "0",
        phone_code: "47",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 210,
        name: "Swaziland",
        short_code: "SZ",
        long_code: "0",
        phone_code: "268",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 211,
        name: "Sweden",
        short_code: "SE",
        long_code: "0",
        phone_code: "46",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 212,
        name: "Switzerland",
        short_code: "CH",
        long_code: "0",
        phone_code: "41",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 213,
        name: "Syria",
        short_code: "SY",
        long_code: "0",
        phone_code: "963",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 214,
        name: "Taiwan",
        short_code: "TW",
        long_code: "0",
        phone_code: "886",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 215,
        name: "Tajikistan",
        short_code: "TJ",
        long_code: "0",
        phone_code: "992",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 216,
        name: "Tanzania",
        short_code: "TZ",
        long_code: "0",
        phone_code: "255",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 217,
        name: "Thailand",
        short_code: "TH",
        long_code: "0",
        phone_code: "66",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 218,
        name: "Togo",
        short_code: "TG",
        long_code: "0",
        phone_code: "228",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 219,
        name: "Tokelau",
        short_code: "TK",
        long_code: "0",
        phone_code: "690",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 220,
        name: "Tonga",
        short_code: "TO",
        long_code: "0",
        phone_code: "676",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 221,
        name: "Trinidad and Tobago",
        short_code: "TT",
        long_code: "0",
        phone_code: "1868",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 222,
        name: "Tunisia",
        short_code: "TN",
        long_code: "0",
        phone_code: "216",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 223,
        name: "Turkey",
        short_code: "TR",
        long_code: "0",
        phone_code: "90",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 224,
        name: "Turkmenistan",
        short_code: "TM",
        long_code: "0",
        phone_code: "7370",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 225,
        name: "Turks and Caicos Islands",
        short_code: "TC",
        long_code: "0",
        phone_code: "1649",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 226,
        name: "Tuvalu",
        short_code: "TV",
        long_code: "0",
        phone_code: "688",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 227,
        name: "Uganda",
        short_code: "UG",
        long_code: "0",
        phone_code: "256",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 228,
        name: "Ukraine",
        short_code: "UA",
        long_code: "0",
        phone_code: "380",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 229,
        name: "United Arab Emirates",
        short_code: "AE",
        long_code: "0",
        phone_code: "971",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 230,
        name: "United Kingdom",
        short_code: "GB",
        long_code: "0",
        phone_code: "44",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 231,
        name: "United States",
        short_code: "US",
        long_code: "0",
        phone_code: "1",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 232,
        name: "countries.united_states_minor_outlying_islands",
        short_code: "UM",
        long_code: "0",
        phone_code: "1",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 233,
        name: "Uruguay",
        short_code: "UY",
        long_code: "0",
        phone_code: "598",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 234,
        name: "Uzbekistan",
        short_code: "UZ",
        long_code: "0",
        phone_code: "998",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 235,
        name: "Vanuatu",
        short_code: "VU",
        long_code: "0",
        phone_code: "678",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 236,
        name: "countries.vatican_city_state_holy_see",
        short_code: "VA",
        long_code: "0",
        phone_code: "39",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 237,
        name: "Venezuela",
        short_code: "VE",
        long_code: "0",
        phone_code: "58",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 238,
        name: "Vietnam",
        short_code: "VN",
        long_code: "0",
        phone_code: "84",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 239,
        name: "countries.virgin_islands_british",
        short_code: "VG",
        long_code: "0",
        phone_code: "1284",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 240,
        name: "countries.virgin_islands_us",
        short_code: "VI",
        long_code: "0",
        phone_code: "1340",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 241,
        name: "countries.wallis_and_futuna_islands",
        short_code: "WF",
        long_code: "0",
        phone_code: "681",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 242,
        name: "Western Sahara",
        short_code: "EH",
        long_code: "0",
        phone_code: "212",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 243,
        name: "Yemen",
        short_code: "YE",
        long_code: "0",
        phone_code: "967",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 244,
        name: "countries.yugoslavia",
        short_code: "YU",
        long_code: "0",
        phone_code: "38",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 245,
        name: "Zambia",
        short_code: "ZM",
        long_code: "0",
        phone_code: "260",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
    {
        id: 246,
        name: "Zimbabwe",
        short_code: "ZW",
        long_code: "0",
        phone_code: "26",
        phone_format: "0",
        latitude: 0,
        longitude: 0,
        status: "active",
        order_no: 0,
    },
];
